api_version: 0.1
project_id: jarvis-examples-secrets
modules:
  - name: app-with-secrets
    path: .
    agents:
      - name: alpine
        default: true
        image: alpine:latest
    steps:
      - name: use api key
        agent: alpine
        secrets:
          - api-key-test
        command: KEY=$(cat $API_KEY_TEST_FILE); echo "Doing work with API key [$KEY]"
