api_version: 0.1
modules:
  - name: sample-app
    path: .
    agents:
      - name: golang
        default: true
        image: golang:latest
      - name: alpine
        image: alpine:latest
        environment:
          A_VARIABLE: true
    steps:
      - name: build
        command: go build
      - name: test
        agent: alpine
        command: echo "A_VARIABLE=$A_VARIABLE" && ./main
