api_version: 0.1
modules:
  - name: sample-app
    path: .
    agents:
      - name: golang
        default: true
        image: golang:latest
        environment:
          OPTIMISED_BINARY: true
    steps:
      - name: compile and test
        command: go build .
