api_version: 0.1
modules:
  - name: sample-app
    path: .
    agents:
      - name: golang
        default: true
        image: golang:latest
        environment:
          OPTIMISED_BINARY: true
      - name: alpine
        image: alpine:latest
    steps:
      - name: build
        command: go build
      - name: test
        agent: alpine
        command: ./main
